Repository the-programmers-hangout/QuestionBot, pull requests merged in 2019-09, with the labels that each got.

#6 Create config service
  README.md
  commands.md
  src/main/kotlin/com/supergrecko/questionbot/QuestionBot.kt
  src/main/kotlin/com/supergrecko/questionbot/arguments/QuestionArg.kt
  src/main/kotlin/com/supergrecko/questionbot/commands/AdminCommands.kt
  src/main/kotlin/com/supergrecko/questionbot/dataclasses/BotConfig.kt
  src/main/kotlin/com/supergrecko/questionbot/listeners/GuildJoinListener.kt
  src/main/kotlin/com/supergrecko/questionbot/listeners/GuildLeaveListener.kt
  src/main/kotlin/com/supergrecko/questionbot/listeners/MessageReceiveListener.kt
  src/main/kotlin/com/supergrecko/questionbot/listeners/ReadyListener.kt
  src/main/kotlin/com/supergrecko/questionbot/services/ConfigService.kt
  src/main/kotlin/com/supergrecko/questionbot/services/InfoService.kt
Labels: scope:dev, type:feature

#7 Create preconditions
  commands.md
  src/main/kotlin/com/supergrecko/questionbot/commands/AnswerCommands.kt
  src/main/kotlin/com/supergrecko/questionbot/commands/ManageCommands.kt
  src/main/kotlin/com/supergrecko/questionbot/commands/QuestionCommands.kt
  src/main/kotlin/com/supergrecko/questionbot/extensions/Command.kt
  src/main/kotlin/com/supergrecko/questionbot/preconditions/PermissionCondition.kt
Labels: scope:dev, type:feature

#8 feature(0.0.0): Create Question argument
  commands.md
  src/main/kotlin/com/supergrecko/questionbot/arguments/QuestionArg.kt
  src/main/kotlin/com/supergrecko/questionbot/extensions/Command.kt
  src/main/kotlin/com/supergrecko/questionbot/extensions/Guild.kt
  src/main/kotlin/com/supergrecko/questionbot/services/QuestionService.kt
Labels: scope:dev, type:feature

#9 feature(0.0.0): Add basic logging for commands
  src/main/kotlin/com/supergrecko/questionbot/commands/AnswerCommands.kt
  src/main/kotlin/com/supergrecko/questionbot/commands/ManageCommands.kt
  src/main/kotlin/com/supergrecko/questionbot/commands/QuestionCommands.kt
  src/main/kotlin/com/supergrecko/questionbot/dataclasses/BotConfig.kt
  src/main/kotlin/com/supergrecko/questionbot/services/LogService.kt
Labels: scope:dev, type:feature

#10 refactor(0.0.0): Make LogService deal with missing log channels in a nicer way
  src/main/kotlin/com/supergrecko/questionbot/dataclasses/BotConfig.kt
  src/main/kotlin/com/supergrecko/questionbot/services/LogService.kt
Labels: scope:dev, type:refactor

#12 Implement ask command
  commands.md
  src/main/kotlin/com/supergrecko/questionbot/commands/ManageCommands.kt
  src/main/kotlin/com/supergrecko/questionbot/commands/QuestionCommands.kt
  src/main/kotlin/com/supergrecko/questionbot/dataclasses/BotConfig.kt
Labels: scope:dev, type:feature

#13 feature(0.0.0): implement setLog command
  commands.md
  src/main/kotlin/com/supergrecko/questionbot/commands/ManageCommands.kt
  src/main/kotlin/com/supergrecko/questionbot/services/ConfigService.kt
Labels: scope:dev, type:feature

#14 patch(0.0.0): Fix cast error
  commands.md
  src/main/kotlin/com/supergrecko/questionbot/commands/ManageCommands.kt
  src/main/kotlin/com/supergrecko/questionbot/services/ConfigService.kt
Labels: scope:dev, type:bugfix

#15 feature(0.0.0): add toggle for logging
  commands.md
  src/main/kotlin/com/supergrecko/questionbot/commands/ManageCommands.kt
  src/main/kotlin/com/supergrecko/questionbot/dataclasses/BotConfig.kt
  src/main/kotlin/com/supergrecko/questionbot/services/ConfigService.kt
  src/main/kotlin/com/supergrecko/questionbot/services/LogService.kt
Labels: scope:dev, type:feature

#16 chore(0.0.0): Fix minor code style issues
  src/main/kotlin/com/supergrecko/questionbot/commands/AnswerCommands.kt
  src/main/kotlin/com/supergrecko/questionbot/commands/ManageCommands.kt
  src/main/kotlin/com/supergrecko/questionbot/commands/QuestionCommands.kt
  src/main/kotlin/com/supergrecko/questionbot/dataclasses/BotConfig.kt
  src/main/kotlin/com/supergrecko/questionbot/preconditions/PermissionCondition.kt
  src/main/kotlin/com/supergrecko/questionbot/services/ConfigService.kt
Labels: scope:dev, type:refactor

#17 feature(0.0.0): Remove TextChannelArg from $ask
  commands.md
  src/main/kotlin/com/supergrecko/questionbot/commands/AnswerCommands.kt
  src/main/kotlin/com/supergrecko/questionbot/commands/ManageCommands.kt
  src/main/kotlin/com/supergrecko/questionbot/commands/QuestionCommands.kt
  src/main/kotlin/com/supergrecko/questionbot/dataclasses/BotConfig.kt
  src/main/kotlin/com/supergrecko/questionbot/preconditions/PermissionCondition.kt
  src/main/kotlin/com/supergrecko/questionbot/services/ConfigService.kt
  src/main/kotlin/com/supergrecko/questionbot/services/QuestionService.kt
Labels: scope:dev, type:feature, type:refactor

#18 feature(0.0.0): implement edit question command
  commands.md
  src/main/kotlin/com/supergrecko/questionbot/commands/QuestionCommands.kt
  src/main/kotlin/com/supergrecko/questionbot/dataclasses/BotConfig.kt
  src/main/kotlin/com/supergrecko/questionbot/services/QuestionService.kt
Labels: scope:dev, type:feature

#19 refactor(0.0.0): Clean up codebase
  commands.md
  src/main/kotlin/com/supergrecko/questionbot/arguments/QuestionArg.kt
  src/main/kotlin/com/supergrecko/questionbot/commands/AnswerCommands.kt
  src/main/kotlin/com/supergrecko/questionbot/commands/ManageCommands.kt
  src/main/kotlin/com/supergrecko/questionbot/commands/QuestionCommands.kt
  src/main/kotlin/com/supergrecko/questionbot/dataclasses/BotConfig.kt
  src/main/kotlin/com/supergrecko/questionbot/extensions/Guild.kt
  src/main/kotlin/com/supergrecko/questionbot/preconditions/PermissionCondition.kt
  src/main/kotlin/com/supergrecko/questionbot/services/ConfigService.kt
  src/main/kotlin/com/supergrecko/questionbot/services/LogService.kt
  src/main/kotlin/com/supergrecko/questionbot/services/QuestionService.kt
  src/main/kotlin/com/supergrecko/questionbot/tools/Arguments.kt
Labels: scope:dev, type:feature, type:refactor

#20 refactor(0.0.0): Make a GuildChannels data class for channels
  src/main/kotlin/com/supergrecko/questionbot/dataclasses/BotConfig.kt
  src/main/kotlin/com/supergrecko/questionbot/services/ConfigService.kt
  src/main/kotlin/com/supergrecko/questionbot/services/LogService.kt
  src/main/kotlin/com/supergrecko/questionbot/services/QuestionService.kt
Labels: scope:dev, type:refactor

#21 refactor(0.0.0): Remove embeds from command responses and clean up log embed
  src/main/kotlin/com/supergrecko/questionbot/commands/ManageCommands.kt
  src/main/kotlin/com/supergrecko/questionbot/listeners/GuildJoinListener.kt
  src/main/kotlin/com/supergrecko/questionbot/listeners/GuildLeaveListener.kt
  src/main/kotlin/com/supergrecko/questionbot/services/LogService.kt
Labels: scope:dev, type:refactor

#22 refactor(0.0.0): Make $setchannel take a channel argument
  commands.md
  src/main/kotlin/com/supergrecko/questionbot/commands/ManageCommands.kt
  src/main/kotlin/com/supergrecko/questionbot/services/ConfigService.kt
Labels: scope:dev, type:refactor

#23 feature(0.0.0): Create the $setrole command
  commands.md
  src/main/kotlin/com/supergrecko/questionbot/commands/ManageCommands.kt
  src/main/kotlin/com/supergrecko/questionbot/services/ConfigService.kt
Labels: scope:dev, type:feature

#24 feature(0.0.0): implement answer command
  commands.md
  src/main/kotlin/com/supergrecko/questionbot/commands/AnswerCommands.kt
  src/main/kotlin/com/supergrecko/questionbot/dataclasses/AnswerDetails.kt
  src/main/kotlin/com/supergrecko/questionbot/dataclasses/BotConfig.kt
  src/main/kotlin/com/supergrecko/questionbot/services/AnswerService.kt
  src/main/kotlin/com/supergrecko/questionbot/services/QuestionService.kt
Labels: scope:dev, type:feature

#26 Update kutils
  commands.md
  pom.xml
  src/main/kotlin/com/supergrecko/questionbot/commands/ManageCommands.kt
Labels: scope:dev, type:refactor

#25 patch(0.0.0): add channel as mention instead of name
  src/main/kotlin/com/supergrecko/questionbot/commands/AnswerCommands.kt
  src/main/kotlin/com/supergrecko/questionbot/services/QuestionService.kt
Labels: scope:dev, type:refactor

#27 refactor(0.0.0): Update embeds
  src/main/kotlin/com/supergrecko/questionbot/commands/ManageCommands.kt
  src/main/kotlin/com/supergrecko/questionbot/dataclasses/BotConfig.kt
  src/main/kotlin/com/supergrecko/questionbot/services/AnswerService.kt
  src/main/kotlin/com/supergrecko/questionbot/services/ConfigService.kt
  src/main/kotlin/com/supergrecko/questionbot/services/LogService.kt
  src/main/kotlin/com/supergrecko/questionbot/services/QuestionService.kt
Labels: scope:dev, type:refactor

#28 feature(0.0.0): Merge $question delete / ask and implement delete.
  commands.md
  src/main/kotlin/com/supergrecko/questionbot/commands/QuestionCommands.kt
  src/main/kotlin/com/supergrecko/questionbot/dataclasses/BotConfig.kt
  src/main/kotlin/com/supergrecko/questionbot/services/QuestionService.kt
Labels: scope:dev, type:feature, type:refactor

#30 feature(0.0.0): implement edit and delete answer commands
  commands.md
  src/main/kotlin/com/supergrecko/questionbot/commands/AnswerCommands.kt
  src/main/kotlin/com/supergrecko/questionbot/dataclasses/BotConfig.kt
  src/main/kotlin/com/supergrecko/questionbot/services/AnswerService.kt
Labels: scope:dev, type:feature

#31 feature(0.0.0): add list command & update embeds
  commands.md
  pom.xml
  src/main/kotlin/com/supergrecko/questionbot/commands/AnswerCommands.kt
  src/main/kotlin/com/supergrecko/questionbot/services/AnswerService.kt
Labels: scope:dev, type:feature

#32 refactor(0.0.0): Refactor names and add answer deletion
  src/main/kotlin/com/supergrecko/questionbot/arguments/QuestionArg.kt
  src/main/kotlin/com/supergrecko/questionbot/dataclasses/Answer.kt
  src/main/kotlin/com/supergrecko/questionbot/dataclasses/BotConfig.kt
  src/main/kotlin/com/supergrecko/questionbot/dataclasses/GuildChannels.kt
  src/main/kotlin/com/supergrecko/questionbot/dataclasses/GuildConfig.kt
  src/main/kotlin/com/supergrecko/questionbot/dataclasses/Question.kt
  src/main/kotlin/com/supergrecko/questionbot/preconditions/PermissionCondition.kt
  src/main/kotlin/com/supergrecko/questionbot/services/AnswerService.kt
  src/main/kotlin/com/supergrecko/questionbot/services/ConfigService.kt
  src/main/kotlin/com/supergrecko/questionbot/services/QuestionService.kt
Labels: scope:dev, type:feature, type:refactor

#35 docs: Add images docs
  .github/assets/commands/ask-example.png
  .github/assets/commands/edit-delete-example.png
  .github/assets/commands/edit-example-1.png
  .github/assets/commands/edit-example-2.png
  .github/assets/commands/logging-example.png
  .github/assets/commands/setchannel-example.png
  .github/assets/commands/setprefix-example.png
  .github/assets/commands/setrole-example.png
  .github/assets/example-run-config.png
  docs/command-manage.md
  docs/commands-ask.md
  docs/development.md
Labels: scope:docs, type:feature

#36 feature(0.0.0): Add onJoin / onLeave listeners
  src/main/kotlin/com/supergrecko/questionbot/listeners/GuildJoinListener.kt
  src/main/kotlin/com/supergrecko/questionbot/listeners/GuildLeaveListener.kt
  src/main/kotlin/com/supergrecko/questionbot/services/ConfigService.kt
Labels: scope:dev, type:feature

#37 refactor(0.0.0): Add KDoc to everything and refactor unused and redundant bits
  src/main/kotlin/com/supergrecko/questionbot/arguments/QuestionArg.kt
  src/main/kotlin/com/supergrecko/questionbot/commands/AnswerCommands.kt
  src/main/kotlin/com/supergrecko/questionbot/commands/ManageCommands.kt
  src/main/kotlin/com/supergrecko/questionbot/commands/QuestionCommands.kt
  src/main/kotlin/com/supergrecko/questionbot/dataclasses/Answer.kt
  src/main/kotlin/com/supergrecko/questionbot/dataclasses/AnswerDetails.kt
  src/main/kotlin/com/supergrecko/questionbot/dataclasses/BotConfig.kt
  src/main/kotlin/com/supergrecko/questionbot/dataclasses/GuildChannels.kt
  src/main/kotlin/com/supergrecko/questionbot/dataclasses/GuildConfig.kt
  src/main/kotlin/com/supergrecko/questionbot/dataclasses/Question.kt
  src/main/kotlin/com/supergrecko/questionbot/listeners/GuildJoinListener.kt
  src/main/kotlin/com/supergrecko/questionbot/listeners/GuildLeaveListener.kt
  src/main/kotlin/com/supergrecko/questionbot/preconditions/PermissionCondition.kt
  src/main/kotlin/com/supergrecko/questionbot/services/AnswerService.kt
  src/main/kotlin/com/supergrecko/questionbot/services/ConfigService.kt
Labels: scope:dev, type:refactor

#40 docs: Fix links, update deployment and add answers
  docs/command-manage.md
  docs/commands-answer.md
  docs/commands-ask.md
  docs/deployment.md
  scripts/deploy.sh
Labels: scope:docs

#41 feature(0.0.0): Set up visibility predicate
  commands.md
  src/main/kotlin/com/supergrecko/questionbot/commands/AnswerCommands.kt
  src/main/kotlin/com/supergrecko/questionbot/commands/ManageCommands.kt
  src/main/kotlin/com/supergrecko/questionbot/commands/QuestionCommands.kt
  src/main/kotlin/com/supergrecko/questionbot/services/VisibilityService.kt
Labels: scope:dev, type:feature

#43 refactor(0.0.0): Remove redundant and unused comments
  .gitignore
  docs/deployment.md
  src/main/kotlin/com/supergrecko/questionbot/commands/AnswerCommands.kt
  src/main/kotlin/com/supergrecko/questionbot/dataclasses/Answer.kt
  src/main/kotlin/com/supergrecko/questionbot/dataclasses/AnswerDetails.kt
  src/main/kotlin/com/supergrecko/questionbot/dataclasses/BotConfig.kt
  src/main/kotlin/com/supergrecko/questionbot/dataclasses/GuildConfig.kt
  src/main/kotlin/com/supergrecko/questionbot/dataclasses/Question.kt
  src/main/kotlin/com/supergrecko/questionbot/services/AnswerService.kt
  src/main/kotlin/com/supergrecko/questionbot/services/ConfigService.kt
  src/main/kotlin/com/supergrecko/questionbot/services/InfoService.kt
  src/main/kotlin/com/supergrecko/questionbot/services/LogService.kt
  src/main/kotlin/com/supergrecko/questionbot/services/QuestionService.kt
  src/main/kotlin/com/supergrecko/questionbot/tools/Arguments.kt
Labels: scope:dev, type:refactor

#44 feature(0.0.0): Add question embed update on prefix change
  src/main/kotlin/com/supergrecko/questionbot/commands/ManageCommands.kt
  src/main/kotlin/com/supergrecko/questionbot/listeners/ReadyListener.kt
  src/main/kotlin/com/supergrecko/questionbot/services/ConfigService.kt
  src/main/kotlin/com/supergrecko/questionbot/services/QuestionService.kt
Labels: scope:dev, type:feature

#45 docs(0.0.0): Add images to answer examples
  .github/assets/commands/answer-delete-example.png
  .github/assets/commands/answer-edit-example-1.png
  .github/assets/commands/answer-edit-example-2.png
  .github/assets/commands/answer-example-1.png
  .github/assets/commands/answer-example-2.png
  .github/assets/commands/answer-list-example.png
  .github/assets/commands/ask-example.png
  README.md
  docs/commands-answer.md
  docs/deployment.md
  docs/development.md
Labels: scope:docs

#46 feature(0.0.0): add management and util commands
  .github/assets/commands/addanswer-answer.png
  .github/assets/commands/addanswer-id.png
  .github/assets/commands/addanswer-mention.png
  .github/assets/commands/delanswer-id.png
  .github/assets/commands/delanswer-mention.png
  commands.md
  docs/command-manage.md
  src/main/kotlin/com/supergrecko/questionbot/commands/ManageCommands.kt
  src/main/kotlin/com/supergrecko/questionbot/commands/UtilityCommands.kt
Labels: scope:dev, type:feature

#47 refactor(0.0.0): Remove wildcard imports and fix category names
  commands.md
  src/main/kotlin/com/supergrecko/questionbot/QuestionBot.kt
  src/main/kotlin/com/supergrecko/questionbot/commands/AnswerCommands.kt
  src/main/kotlin/com/supergrecko/questionbot/commands/ManageCommands.kt
  src/main/kotlin/com/supergrecko/questionbot/commands/QuestionCommands.kt
  src/main/kotlin/com/supergrecko/questionbot/commands/UtilityCommands.kt
Labels: scope:dev, type:refactor

#48 feature(0.0.0): Make Answer embed show highest rank color (requested by Elliott)
  src/main/kotlin/com/supergrecko/questionbot/services/AnswerService.kt
Labels: scope:dev, type:feature
